#docker-compose.yml #version: '3.8'
services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django_ncs_app
    image: ncs-web
    volumes:
      # Mount the project directory
      - .:/usr/src/app
      # Mount the static files directory to be shared with Nginx
      - ./ncs/static:/usr/src/app/static_collected
    ports:
      # Expose the Gunicorn port for Nginx to access it internally
      - "8000:8000"
    restart: unless-stopped
      
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_ncs_proxy
    #image: nginx:1.21.3-alpine
    image: nginx-alpine
    volumes:
      # Mount the Nginx configuration file
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Mount the static files directory from the web container
      - ./ncs/static:/usr/src/app/static_collected
    ports:
      # Expose port 80 to the host machine
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped